name: Skyblock
version: '1.1'
main: net.teuos.skyblock.Skyblock
api-version: '1.21'
authors: [ teuos ]
description: A skyblock core plugin
commands:
  island:
    description: Skyblock island commands